version: '3'
services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./tests/db:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=comp1640
        ports:
            - 3306:3306
    app:
        build:
            context: .
        links:
            - mysql
        depends_on:
            - mysql
        volumes:
            - .:/var/www/:cached
            - /var/www/vendor/
            - /var/www/node_modules
        command: bin/console server:run 0.0.0.0:80
        ports:
            - 80:80
